### ISSUE TITLE
Error while looting on Amazon Games

### ISSUE THREAD

**Issue by Kraker01** [sibalzer/primelooter#22]
Hi, i'm experiencing this error: 

`[ERROR] Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...6d8'}, ...}}}>) at C:\Python39\lib\site-packages\playwright\_impl\_sync_base.py:104
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...6d8'}, ...}}}>) at C:\Python39\lib\site-packages\playwright\_impl\_sync_base.py:104>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python39\lib\site-packages\playwright\_impl\_sync_base.py", line 105, in callback
    g_self.switch()
  File "C:\Python39\lib\site-packages\playwright\_impl\_browser_context.py", line 111, in <lambda>
    lambda params: self._on_response(
  File "C:\Python39\lib\site-packages\playwright\_impl\_browser_context.py", line 361, in _on_response
    page.emit(Page.Events.Response, response)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 115, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 98, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "C:\Python39\lib\site-packages\pyee\_asyncio.py", line 43, in _emit_run
    self.emit("error", exc)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "C:\Python39\lib\site-packages\pyee\_asyncio.py", line 41, in _emit_run
    coro = f(*args, **kwargs)
  File "C:\Python39\lib\site-packages\playwright\_impl\_wait_helper.py", line 121, in listener
    self._fulfill(event_data)
  File "C:\Python39\lib\site-packages\playwright\_impl\_wait_helper.py", line 99, in _fulfill
    self._cleanup()
  File "C:\Python39\lib\site-packages\playwright\_impl\_wait_helper.py", line 96, in _cleanup
    listener[0].remove_listener(listener[1], listener[2])
  File "C:\Python39\lib\site-packages\playwright\_impl\_page.py", line 272, in remove_listener
    super().remove_listener(event, f)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 155, in remove_listener
    self._remove_listener(event, f)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 150, in _remove_listener
    self._events[event].pop(f)`

Primelooter is latest version (1.3.0), i didn't change anything else.

**Comment by sibalzer** [comment]
Since i don't have Prime anymore, this project is no longer maintained. Please use [srhinos fork](https://github.com/srhinos/primelooter).
