### ISSUE TITLE
Error 'NoneType' object has no attribute 'click'

### ISSUE THREAD

**Issue by Kraker01** [sibalzer/primelooter#7]
This is the error i got from 01/09/2021 when trying to loot new games:

2021-09-03 22:47:50 [ERROR] Error 'NoneType' object has no attribute 'click'
  File "C:\Users\Marco\Documents\GitHub\primelooter\primelooter.py", line 229, in <module>
    loot(cookies, publishers, headless, dump)
  File "C:\Users\Marco\Documents\GitHub\primelooter\primelooter.py", line 154, in loot
    elem.query_selector("button[data-a-target=FGWPOffer]").click()

**Comment by sibalzer** [comment]
#8 should fix this.

**Comment by Kraker01** [comment]
Working fine while redeeming games:
2021-09-07 08:17:11 [INFO] Claiming these direct offers:
    - Tools Up!
    - Sam and Max Hit the Road
    - Puzzle Agent
    - Candleman: The Complete Journey
    - Unmemory
    - Secret Files 2: Puritas Cordi
2021-09-07 08:17:21 [INFO] Claimed Tools Up! by All in! Games
2021-09-07 08:17:21 [INFO] Claimed Sam and Max Hit the Road by LucasArts
2021-09-07 08:17:22 [INFO] Claimed Puzzle Agent by Telltale
2021-09-07 08:17:23 [INFO] Claimed Candleman: The Complete Journey by Thermite Games
2021-09-07 08:17:24 [INFO] Claimed Unmemory by Plug In Digital
2021-09-07 08:17:25 [INFO] Claimed Secret Files 2: Puritas Cordis by Deep Silver

Experiencing problems while redeeming offers for DLC:

2021-09-07 08:18:01 [ERROR] Exception in callback SyncBase._sync.<locals>.callback(<Task finishe... ...}, ...}}}>) at C:\Python39\lib\site-packages\playwright\_impl\_sync_base.py:104
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe... ...}, ...}}}>) at C:\Python39\lib\site-packages\playwright\_impl\_sync_base.py:104>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python39\lib\site-packages\playwright\_impl\_sync_base.py", line 105, in callback
    g_self.switch()
  File "C:\Python39\lib\site-packages\playwright\_impl\_browser_context.py", line 111, in <lambda>
    lambda params: self._on_response(
  File "C:\Python39\lib\site-packages\playwright\_impl\_browser_context.py", line 361, in _on_response
    page.emit(Page.Events.Response, response)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 115, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 98, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "C:\Python39\lib\site-packages\pyee\_asyncio.py", line 43, in _emit_run
    self.emit("error", exc)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "C:\Python39\lib\site-packages\pyee\_asyncio.py", line 41, in _emit_run
    coro = f(*args, **kwargs)
  File "C:\Python39\lib\site-packages\playwright\_impl\_wait_helper.py", line 121, in listener
    self._fulfill(event_data)
  File "C:\Python39\lib\site-packages\playwright\_impl\_wait_helper.py", line 99, in _fulfill
    self._cleanup()
  File "C:\Python39\lib\site-packages\playwright\_impl\_wait_helper.py", line 96, in _cleanup
    listener[0].remove_listener(listener[1], listener[2])
  File "C:\Python39\lib\site-packages\playwright\_impl\_page.py", line 272, in remove_listener
    super().remove_listener(event, f)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 155, in remove_listener
    self._remove_listener(event, f)
  File "C:\Python39\lib\site-packages\pyee\_base.py", line 150, in _remove_listener
    self._events[event].pop(f)
KeyError: <function WaitHelper.reject_on_event.<locals>.listener at 0x000001381834A280>

**Comment by sibalzer** [comment]
Sorry for the late reply, but I can't reproduce this error. Does it still occur?

**Comment by sibalzer** [comment]
Guss it's fixed. Please reopen or create a new Issue if it happens again.
